version: "3"

services:
  nginx:
    image: nginx:1.15.7-alpine
    ports:
     - "80:80"
    volumes:
     - "./config/default.conf:/etc/nginx/conf.d/default.conf:ro"
     - "./public_html/:/var/www/html/:rw"
    depends_on:
     - mysql
     
  php:
    build: ./php/
    volumes:
     - "./public_html/:/var/www/html/:rw" 
    depends_on:
     - mysql

  mysql: 
    build: ./mysql/
    ports:
     - "3306:3306"
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: wordpress
     MYSQL_USER: kojiro
     MYSQL_PASSWORD: kojiro

  debug:
      build: ./debug/
      tty: true
